clear all;
close all;
[audio_in, fs] = audioread('sa_re_ga_ma.mp3');
sound(audio_in,fs);
disp('Normal Speed');
pause(30);
double_speed = resample(audio_in,1,2);
disp('Playing double speed');
sound(double_speed,fs);
pause(16);
disp('playing half Speed');
half_speed = resample(audio_in,2,1);
sound(half_speed,fs);
figure;
subplot(3,1,1);
plot(audio_in);
title("Normal Speed");
subplot(3,1,2);
plot(double_speed);
title("Double Speed");
subplot(3,1,3);
plot(half_speed);
title("Half Speed");
